disabled_rules:
  - switch_case_alignment
  - unneeded_break_in_switch
  - multiple_closures_with_trailing_closure
excluded:
  - Pods
line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true
